---

- set_fact: java_state="present"

- when: update_java == true
  set_fact: java_state="latest"

- when: ansible_os_family == 'RedHat'
  name: RedHat - Ensure Java is installed
  yum: 
    name: "{{ java }}" 
    state: "{{java_state}}"
  
- when: ansible_os_family == 'Debian'
  name: Debian - Ensure Java is installed
  apt: 
    name: "{{ java }}" 
    state: "{{java_state}}" 
    update_cache: yes 
    force: yes

- command: java -version 2>&1 | grep OpenJDK
  register: open_jdk

- when: ansible_distribution == 'Ubuntu' and open_jdk.rc == 0
  name: refresh the java ca-certificates
  command: /var/lib/dpkg/info/ca-certificates-java.postinst configure

