---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
    - always

- name: check-set-parameters
  include: elasticsearch-parameters.yml
  tags:
    - check
    - always

- when: _debug
  include: _debug.yml
  tags: 
    - debug


- when: es_java_install
  include: java.yml
  tags:
    - java

- include: "elasticsearch-{{ansible_os_family}}.yml"
  tags:
    - install

- include: elasticsearch-config.yml
  tags:
      - config
       
- meta: flush_handlers
    

